name: Run Pytest on push

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        auto-update-conda: true
        activate-environment: conda-environment
        environment-file: .github/environment.yml

    - name: Install MMC package
      run: conda run -n conda-environment pip install .

    - name: Run pytest
      run: conda run -n conda-environment pytest tests/test_initial_energies.py tests/test_driver_zeeman.py
