name: Run Pytest on push

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        auto-update-conda: true
        activate-environment: conda-environment
        environment-file: .github/environment.yml
    
    # - name: Update conda environment
    #   run: conda update --all

    # - name: Set up Python
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: 3.8 

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r tests/test_requirements.txt
        pip install -e .

    # - name: Install OOMMF using conda
    #   run: conda install -c conda-forge oommf
    
    # - name: Install Ubermag using conda
    #   run: conda install -c conda-forge ubermag

    # - name: Pull Docker image
    #   run: docker pull oommf/oommf

    # - name: Run pytest
    #   run: |
    #     conda info --envs
    #     conda activate base
    #     conda activate conda-environment
    #     pytest tests/test_initial_energies.py

    - name: Run pytest
      run: conda run -n conda-environment pytest tests/test_initial_energies.py

# name: unit_tests

# on:
#   push:
#     branches:
#       - master

# env:
#   PYTEST_ADDOPTS: "--color=yes"

# jobs:
#   workflow:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         os: [ubuntu-latest, macos-latest, windows-latest]
#         python-version: ["3.8", "3.10"]
#     defaults:
#       run:
#         shell: bash -l {0}

#     steps:
#     - name: Initialisation
#       uses: actions/checkout@v4

#     - name: Set up conda
#       uses: conda-incubator/setup-miniconda@v2
#       with:
#         python-version: ${{ matrix.python-version }}
#         auto-update-conda: true
#         activate-environment: conda-environment
#         environment-file: .github/environment.yml

#     - name: Install package
#       run: |
#         python -m pip install .[dev]
#         pip install --upgrade pip
#         pip install -r tests/test_requirements.txt
#         pip install -e .

#     - name: Unit tests
#       run: pytest tests/test_initial_energies.py